feat: adapt to rst
all-contributors/cli pull request #301
Opened 2021-04-30 11:43 UTC by 12rambau

Adapt the indentation level of what's written to the initial indent of the opening tag. It should change nothing to markdown input.

**What**:
The table and badge created by the CLI are raw HTML. They cannot be used in .rst fie because RST files are sensible to indentation. To be compatible the tool should get the indentation of the first tag and apply it to the rest of the content (as a global offset). #300 

**Why**:
To make the tool compatible with .rst file => every doc created with Sphinx 

**How**:
I'm getting the index of the last `\n` before the start Tag and I then replace every `\n`of the newcontent with an appropriate number of extra spaces. 

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged 
- [ ] Added myself to contributors table 

**Comments**
I don't want/can add nodes dependencies to my project (that's why I was interested by the bot) so I can't test this functionality myself. I've authorized the edit by maintainer but let me know if I need to change things on my side.

2021-06-26 22:04 UTC, Berkmann18 reviewed
I tried pushing changes but it blocked me so I'll just write the changes as suggestions.

2021-06-26 22:09 UTC, Berkmann18 requested changes
The tests need to be updated as well (one of the updates would require a local command, unless you fancy manually updating snapshots):
![image](https://user-images.githubusercontent.com/8260834/123526982-87387600-d6d3-11eb-9557-d8ca53904003.png)

2021-06-26 22:09 UTC, Berkmann18 commented on src/generate/index.js
> +    const nbSpaces = startOfOpeningTagIndex - min(startOfOpeningTagIndex, startIndent)
```suggestion
    const startIndent = Math.max(0, previousContent.lastIndexOf('\n', startOfOpeningTagIndex))
    const nbSpaces = startOfOpeningTagIndex - Math.min(startOfOpeningTagIndex, startIndent)
```

2021-06-26 22:09 UTC, Berkmann18 commented on src/generate/index.js
> +      newContent.replace('\n', '\n'+ ' '.repeat(nbSpaces)),
```suggestion
      newContent.replace('\n', '\n' + ' '.repeat(nbSpaces)),
```

2021-06-26 22:09 UTC, Berkmann18 commented on src/generate/index.js
> +    const nbSpaces = startOfOpeningTagIndex - min(startOfOpeningTagIndex, startIndent)
```suggestion
    const startIndent = Math.max(0, previousContent.lastIndexOf('\n', startOfOpeningTagIndex))
    const nbSpaces = startOfOpeningTagIndex - Math.min(startOfOpeningTagIndex, startIndent)
```

2021-06-26 22:09 UTC, Berkmann18 commented on src/generate/index.js
> +      newContent.replace('\n', '\n'+ ' '.repeat(nbSpaces)),
```suggestion
      newContent.replace('\n', '\n' + ' '.repeat(nbSpaces)),
```

2021-06-29 09:53 UTC, 12rambau commented
> I tried pushing changes but it blocked me so I'll just write the changes as suggestions.

this is weird as I set this: 

![Capture d’écran 2021-06-29 à 11 52 37](https://user-images.githubusercontent.com/12596392/123777504-8f113980-d8d0-11eb-96d0-85791067db7c.png)

boh it will just be slowlyer from my side, I'll review them AFAP

2021-06-29 10:45 UTC, 12rambau commented
according to the image you send it seems that something is not running the way I would like, I'm trying to install the yarn project locally but I can't manage to make it work. 

I've cloned my brnach on my local computer and run : `yarn init` in my fake project. Then to install the lib I ran: `yarn add file:/Users/pierrickrambaud/Documents/travail/FAO/app_buffer/all-contributors-cli` which seems to work as well. 

When I check `node_modules/.bin/`, `all-contributor` is nowhere to be found, is it normal ?

2021-07-07 10:21 UTC, Berkmann18 commented
Hmm, if you wanted to install the cli you should have done either:
```
npm i all-contributors-cli
```
or
```
yard add all-contributors-cli
```
Well, assuming you wanted to install it in a project and not as a dev/prod dependency.

2021-09-02 09:12 UTC, 12rambau commented
Sorry for the very late answer but i had no time to dedicate to this PR these past month. 
So as I explained I would like to test the modifications I made on a fake project but i don't understand how node_module works. 

how can I test the cli in "dev" mode ?

2021-11-29 22:45 UTC, Berkmann18 commented
@12rambau That's fine, I was also very busy with other stuff.
The node_modules contain packages installed by NPM with `npm i`.

2021-12-05 13:01 UTC, 12rambau commented
i ran `npm i` which seemed to worked (I'll ignore deprecation warnings) and then `npm t` that led to error in the snapshots as you mentioned. 

Now if I want to use it (the local version from my computer) in a fake folder (to check waht happens) what should I do ? 
If I run `npm start` from the cli folder, I get the following error: 
```
sh: ./dist/cli.js: No such file or directory
```

And obviously the `all-contributor` cli is not available. 
I'm srry if you think that my questions are trivial but there is not contributing section in the doc. i'll be happy to create one onc I finally mange to run it once

2022-01-07 18:47 UTC, Berkmann18 commented
> If I run npm start from the cli folder, I get the following error:

Have you tried running it from the root of the repo?

2022-01-12 08:04 UTC, 12rambau commented
I get the following error : 
```
> all-contributors-cli@0.0.0-semantically-released start /Users/pierrickrambaud/Documents/travail/FAO/app_buffer/all-contributors-cli
> ./dist/cli.js

sh: ./dist/cli.js: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! all-contributors-cli@0.0.0-semantically-released start: `./dist/cli.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the all-contributors-cli@0.0.0-semantically-released start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pierrickrambaud/.npm/_logs/2022-01-12T07_55_41_479Z-debug.log
```

The use case is trivial, I've pulled the repository to my local computer, created a fake repository with nothing in it but a `README.md` file. I just want to start the CLI locally (using my branch and not the distant package) and check the output of the commands in this very repository. Once done I'll be able to modify the snapshot and finish this PR. 

I'm sure it's 101 developing procedure. can you write down the steps to reproduce it from my end ?

2022-09-27 15:28 UTC, tenshiAMD commented
@12rambau I've fixed the checks. do you mind adding some tests? Thanks.

2022-09-27 16:06 UTC, 12rambau commented
first thank you very much for taking over the review of this PR ! 
I would be glad to help but as long as I don't understand how to start it locally I won't be able to do anything. If you look at my previous exchange you will realize that I barely understand how I'm supposed to use this tool locally (I'm actually interested by the bot in the first place). I let you decide if it's more time-consuming for you to explain to me or to write the tests yourself.

2022-09-27 16:42 UTC, tenshiAMD commented
@Berkmann18 I tested both .md and .rst are working

2022-09-27 16:46 UTC, tenshiAMD approved these changes

2022-09-27 16:50 UTC, tenshiAMD commented
@all-contributors please add @12rambau for code

2022-09-27 17:07 UTC, merged

2022-09-28 14:40 UTC, tenshiAMD commented
> I'll wait until it's available via the bot to test it in my Python projects

@12rambau you can try now